import { AlertTriangle, ShieldCheck, Info, XCircle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { type ReactNode } from 'react';

interface AlertProps {
  variant?: 'info' | 'success' | 'warning' | 'danger';
  title?: string;
  children: ReactNode;
  className?: string;
}

const alertConfig = {
  info: { icon: Info, bg: 'bg-blue-50', border: 'border-blue-200', text: 'text-blue-800', iconColor: 'text-blue-500' },
  success: { icon: ShieldCheck, bg: 'bg-success-50', border: 'border-success-200', text: 'text-success-800', iconColor: 'text-success-500' },
  warning: { icon: AlertTriangle, bg: 'bg-warning-50', border: 'border-warning-200', text: 'text-warning-800', iconColor: 'text-warning-500' },
  danger: { icon: XCircle, bg: 'bg-danger-50', border: 'border-danger-200', text: 'text-danger-800', iconColor: 'text-danger-500' },
};

export function Alert({ variant = 'info', title, children, className }: AlertProps) {
  const config = alertConfig[variant];
  const Icon = config.icon;

  return (
    <div className={cn('flex gap-3 rounded-lg border px-4 py-3', config.bg, config.border, className)}>
      <Icon size={18} className={cn('flex-shrink-0 mt-0.5', config.iconColor)} />
      <div className={cn('text-sm', config.text)}>
        {title && <p className="font-semibold mb-0.5">{title}</p>}
        {children}
      </div>
    </div>
  );
}

interface AIDisclaimerProps {
  className?: string;
}

export function AIDisclaimer({ className }: AIDisclaimerProps) {
  return (
    <Alert variant="warning" className={className}>
      <p className="font-semibold">AI-assisted investigation support. Results require verification by authorized investigators and should not be treated as legal conclusions.</p>
      <p className="mt-0.5">
        These results are generated by an AI system to support investigation workflows.
        They do not represent legal certainty and must be independently verified by a qualified investigator.
        Confidence scores reflect statement consistency and observation quality, not guilt or innocence.
      </p>
    </Alert>
  );
}

interface LoadingStateProps {
  message?: string;
  className?: string;
}

export function LoadingState({ message = 'Processing...', className }: LoadingStateProps) {
  return (
    <div className={cn('flex items-center gap-3 text-slate-500', className)}>
      <Loader2 size={18} className="animate-spin text-primary-500" />
      <span className="text-sm font-medium">{message}</span>
    </div>
  );
}

interface ProgressBarProps {
  value: number;
  className?: string;
  color?: string;
}

export function ProgressBar({ value, className, color }: ProgressBarProps) {
  const barColor = color ?? (value >= 75 ? 'bg-success-500' : value >= 55 ? 'bg-warning-500' : 'bg-danger-500');
  return (
    <div className={cn('h-2 rounded-full bg-slate-100 overflow-hidden', className)}>
      <div
        className={cn('h-full rounded-full transition-all duration-700 ease-out', barColor)}
        style={{ width: `${value}%` }}
      />
    </div>
  );
}
